
#Reward Model Parameters
novelty: 1.0
depth: 0.2


#PPO Trainer Parameters
model_name: "Qwen/Qwen2.5-3B-Instruct"
num_iterations: 5

concept_graph_path: "concept_graph.json"
question_bank_path: "question_bank.json"