name: question_generation
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - arrow-cpp=21.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - black=25.9.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - datasets=2.12.0
  - dill=0.3.6
  - expat=2.7.1
  - filelock=3.17.0
  - frozenlist=1.8.0
  - gettext=0.21.0
  - gflags=2.2.2
  - glog=0.5.0
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - icu=73.1
  - intel-openmp=2025.0.0
  - ld_impl_linux-64=2.44
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.16.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libnghttp2=1.57.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - multidict=6.7.0
  - multiprocess=0.70.14
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - numexpr=2.11.0
  - openssl=3.0.18
  - orc=2.2.0
  - pandas=2.3.3
  - pathspec=0.12.1
  - pip=25.2
  - platformdirs=4.3.7
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytokens=0.2.0
  - re2=2024.07.02
  - readline=8.3
  - regex=2025.9.1
  - requests=2.32.5
  - responses=0.13.3
  - s2n=1.5.14
  - safetensors=0.5.3
  - setuptools=80.9.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tokenizers=0.21.0
  - tomli=2.2.1
  - tqdm=4.67.1
  - transformers=4.51.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yarl=1.18.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.11.0
      - annotated-doc==0.0.3
      - anyio==4.11.0
      - asttokens==3.0.1
      - async-timeout==4.0.3
      - attrs==25.4.0
      - bitsandbytes==0.48.2
      - blinker==1.9.0
      - brotli==1.1.0
      - certifi==2025.10.5
      - click==8.3.0
      - contourpy==1.3.2
      - cryptography==45.0.7
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - diffusers==0.35.2
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - faiss-cpu==1.12.0
      - faiss-gpu==1.7.2
      - fastapi==0.120.2
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - fsspec==2025.3.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - importlib-metadata==8.7.0
      - ipython==8.37.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain==1.0.2
      - langchain-classic==1.0.0
      - langchain-community==0.4
      - langchain-core==1.0.0
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.37
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mypy-extensions==1.1.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.15.0
      - ordered-set==4.1.0
      - orjson==3.11.3
      - ormsgpack==1.11.0
      - packaging==25.0
      - parso==0.8.5
      - peft==0.17.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylatex==1.4.2
      - pymongo==4.15.3
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyvis==0.3.1
      - pyyaml==6.0.3
      - reportlab==4.4.5
      - requests-toolbelt==1.0.0
      - rewardanything==1.0.1
      - rich==14.2.0
      - sentence-transformers==5.1.1
      - sentencepiece==0.2.1
      - shtab==1.7.2
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - stack-data==0.6.3
      - starlette==0.49.1
      - tenacity==9.1.2
      - torch==2.9.0
      - traitlets==5.14.3
      - triton==3.5.0
      - trl==0.9.6
      - typeguard==4.4.4
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - uvicorn==0.38.0
      - wandb==0.22.2
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - zipp==3.23.0
      - zstandard==0.25.0
