_wandb:
    value:
        cli_version: 0.22.2
        e:
            ic39b580rzd5tysc7ovjza5mc6mwbd6d:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "872059330560"
                        used: "865841184768"
                email: ae21b026@smail.iitm.ac.in
                executable: /home/ae21b026/miniconda3/envs/question_generation/bin/python
                git:
                    commit: 60e8dec79a57b5db78c2e9f3a8428b5fc8a3cc93
                    remote: https://github.com/jaygupta907/RL4Education.git
                gpu: Tesla V100-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-36b58b0b-492c-e161-c734-fc2bae860215
                host: e2e-70-32
                memory:
                    total: "123639959552"
                os: Linux-5.15.0-153-generic-x86_64-with-glibc2.35
                program: /home/ae21b026/RL4Education/main.py
                python: CPython 3.10.18
                root: /home/ae21b026/RL4Education
                startedAt: "2025-10-30T16:46:56.523818Z"
                writerId: ic39b580rzd5tysc7ovjza5mc6mwbd6d
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 84
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 84
                - 98
                - 105
            "3":
                - 13
            "4": 3.10.18
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
