_wandb:
    value:
        cli_version: 0.22.2
        e:
            oai3teoyc8t38f49uxng2s4mykro1zdu:
                codePath: Procedural_knowledge/finetune_question_generator.py
                codePathLocal: finetune_question_generator.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "872059330560"
                        used: "811577417728"
                email: ae21b026@smail.iitm.ac.in
                executable: /home/ae21b026/miniconda3/envs/question_generation/bin/python
                git:
                    commit: f5de735d28b60d7cd382b2a806bd575b8b4614bd
                    remote: git@github.com:jaygupta907/RL4Education.git
                gpu: Tesla V100-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-36b58b0b-492c-e161-c734-fc2bae860215
                host: e2e-70-32
                memory:
                    total: "123639959552"
                os: Linux-5.15.0-153-generic-x86_64-with-glibc2.35
                program: /home/ae21b026/RL4Education/Procedural_knowledge/finetune_question_generator.py
                python: CPython 3.10.18
                root: /home/ae21b026/RL4Education/Procedural_knowledge
                startedAt: "2026-01-13T14:06:22.295707Z"
                writerId: oai3teoyc8t38f49uxng2s4mykro1zdu
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
                - 105
            "3":
                - 2
                - 24
                - 61
            "4": 3.10.18
            "5": 0.22.2
            "6": 4.51.3
            "12": 0.22.2
            "13": linux-x86_64
trl_ppo_trainer_config:
    value:
        adap_kl_ctrl: true
        backward_batch_size: 1
        batch_size: 1
        cliprange: 0.2
        cliprange_value: 0.2
        compare_steps: 1
        early_stopping: false
        exp_name: finetune_question_generator
        forward_batch_size: null
        gamma: 1
        global_backward_batch_size: 1
        global_batch_size: 1
        gradient_accumulation_steps: 1
        gradient_checkpointing: true
        horizon: 10000
        init_kl_coef: 0.2
        is_encoder_decoder: false
        is_peft_model: false
        kl_penalty: kl
        lam: 0.95
        learning_rate: 1.41e-05
        log_with: wandb
        max_grad_norm: null
        mini_batch_size: 1
        model_name: Qwen/Qwen2.5-3B-Instruct
        optimize_cuda_cache: true
        optimize_device_cache: false
        ppo_epochs: 4
        project_kwargs/logging_dir: ./checkpoints/question_generator_ppo
        query_dataset: imdb
        ratio_threshold: 10
        remove_unused_columns: true
        reward_model: sentiment-analysis:lvwerra/distilbert-imdb
        score_clip: null
        seed: 0
        steps: 20000
        target: 6
        target_kl: 1
        task_name: null
        total_ppo_epochs: 20000
        tracker_project_name: trl
        use_score_norm: false
        use_score_scaling: false
        vf_coef: 0.1
        whiten_rewards: false
        world_size: 1
